name: "build-test"
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - uses: actions/checkout@v2
      - name: Decrypt team settings
        run: ./.github/scripts/decrypt-team-provider.sh
        env:
          PASS_PHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Configure amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
        env:
          GATSBY_TELEMETRY_DISABLED: 1
          INSTAGRAM_API_TOKEN: ${{ secrets.INSTAGRAM_API_TOKEN }}
          INSTAGRAM_BUSINES_ID: ${{ secrets.INSTAGRAM_BUSINES_ID }}
          GTAG_ID: ${{ secrets.GTAG_ID }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          MAILCHIMP_ENDPOINT: ${{ secrets.MAILCHIMP_ENDPOINT }}

      - uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
